import{a as w,S,i as l}from"./assets/vendor-06b1bbdf.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();let g=15;async function x(){let e;i===1?e=u.elements.search.value.trim().split(" ").join("+"):e=y.trim().split(" ").join("+");const s=new URLSearchParams({key:"42996639-9210c4b9e8937070da12bf768",q:[e],image_type:"photo",orientation:"horizontal",safesearch:!0,page:[i],per_page:[g]});return(await w.get(`https://pixabay.com/api/?${s}`)).data}const h=document.querySelector(".gallery"),O=new S(".gallery a",{captionsData:"alt",captionDelay:250});function $(e){const s=e.map(({largeImageURL:r,webformatURL:n,tags:t,likes:o,views:a,comments:L,downloads:P})=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${r}">
            <img class="photo" src="${n}" alt="${t}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${o}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${a}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${L}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${P}</p></li>
            </ul>
            </li>`).join("");h.insertAdjacentHTML("beforeend",s),O.refresh()}const u=document.querySelector(".search-form");let i=1,y="";const c=document.querySelector(".next-page-btn");p(c);const d=document.querySelector(".loader");p(d);let m=1;window.onload=b;u.addEventListener("submit",q);c.addEventListener("click",v);function q(e){e.preventDefault(),h.innerHTML="";const s=e.target.elements.search.value.trim();if(s!=="")i=1,y=s,F();else return l.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}async function F(){try{if(p(c),f(d),i<=m){const e=await x();if(e.totalHits!=0){m=Math.ceil(e.totalHits/g),$(e.hits);const r=h.querySelector(".photos-list-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"}),i<m?f(c):l.info({theme:"dark",progressBarColor:"#FFFFFF",position:"topRight",message:"We're sorry, there are no more images to load"})}else l.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}}catch(e){console.log(e),l.error({message:`${e.message}`,theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}finally{p(d),b(),u.reset()}}function v(){++i,F()}function f(e){e.classList.toggle("hidden"),e.style.display="flex"}function p(e){e.classList.toggle("hidden"),e.style.display="none"}function b(){document.body.classList.add("loaded"),document.body.classList.remove("loaded_hiding")}
//# sourceMappingURL=commonHelpers.js.map
